### ISSUE TITLE
Embed workshop previews

### ISSUE THREAD

**Issue by outkine** [hackclub/v2#155]
There is currently no way to embed JS into a workshop. This is beneficial because having the final result playable right in the page would make it easier and faster to know exactly what you're trying to make.

**Comment by lachlanjc** [comment]
Just to clarify, you’d like the final result embedded on the workshop page?

**Comment by outkine** [comment]
Right. Allow for Javascript in Markdown, basically.

**Comment by merelinguist** [comment]
JS in Markdown isn’t even necessarily required, just an iframe with a CodePen / demo site, right?

**Comment by outkine** [comment]
An iframe should work.

**Comment by merelinguist** [comment]
I likw this idea! You should probably open an issue [here](https://github.com/hackclub/hackclub) to see what they think about adding this to the workshops themselves. Unless I'm missing something, this *should* just work by adding iframes to the workshop markdown files...

**Comment by outkine** [comment]
I'll try using an iframe and will report back. If we want to redo more workshops to use that functionality then we'll need more help - that's a pretty big overhaul.

**Comment by lachlanjc** [comment]
Yep, we can just add previews with an iframe. I think the best course of action would be moving the demo links to workshop frontmatter (`demo`) so we can get that consistently.

**Comment by outkine** [comment]
I'm not sure I follow - isn't the idea that there could be multiple demos per workshop? I don't think that we should constrain that by forcing a frontmatter property.

**Comment by maxwofford** [comment]
How about this: workshops have an optional array of example projects in their markdown metadata. Example:

```yml
name: Personal Website
description: Making your first website from scratch
author: Hack Club staff
group: start
order: 1
examples:
- name: kanye
  link: https://sohuang.github.io/
  author:
    name: "@sohuang"
    link: https://github.com/sohuang
- name: Zero Cool
  link: https://harrison.tech/zero-cool/
  author:
    name: "@paked"
    link: https://harrison.tech/
```

With that data, we can figure out a good design for using the metadata on our frontend (maybe include example links in the header or add a section of iframe'd projects). Thoughts?
